const TARGET_FPS = 30
const TARGET_FRAME_DURATION = (1000 / TARGET_FPS)
const MIN_PARTICLE_SIZE = 0.15
const SIZE_MODIFIER = 0.89

module.exports = {
  TARGET_FPS,
  TARGET_FRAME_DURATION,
  MIN_PARTICLE_SIZE,
  SIZE_MODIFIER
}